version: "3"
services:
  lint-plugin:
    image: 362995399210.dkr.ecr.ap-southeast-2.amazonaws.com/docker.io/buildkite/plugin-linter:v2.1.0
    volumes:
      - ".:/plugin"
    command: 
      - --id 
      - "CatchoftheDay/build-and-push"

  lint-shell:
    image: 362995399210.dkr.ecr.ap-southeast-2.amazonaws.com/docker.io/koalaman/shellcheck:v0.10.0
    volumes:
      - ".:/plugin"
    command:
      - -x
      - /plugin/hooks/command

  lint-python:
    image: public.ecr.aws/docker/library/python:3.7
    volumes:
      - ".:/plugin:ro"
    working_dir: /plugin
    command: sh -c "python3 -m pip install -r requirements.dev.txt && python3 -m pylint pipeline/pipeline.py --ignore-long-lines \".*\""

  tests-python:
    image: public.ecr.aws/docker/library/python:3.7
    volumes:
      - ".:/plugin:ro"
    working_dir: /plugin
    command: sh -c "python3 -m pip install -r requirements.txt && python3 -m unittest discover -s pipeline"
