version: "3"
services:
  lint-plugin:
    image: buildkite/plugin-linter:v2.0.4
    volumes:
      - ".:/plugin"
    command: 
      - --id 
      - "CatchoftheDay/build-and-push"

  lint-shell:
    image: koalaman/shellcheck:v0.9.0
    volumes:
      - ".:/plugin"
    command:
      - -x
      - /plugin/hooks/command

  lint-python:
    image: python:3.11
    volumes:
      - ".:/plugin:ro"
    working_dir: /plugin
    command: sh -c "python3 -m pip install -r requirements.dev.txt && python3 -m pylint pipeline/pipeline.py --ignore-long-lines \".*\""

  tests-python:
    image: python:3.11
    volumes:
      - ".:/plugin:ro"
    working_dir: /plugin
    command: sh -c "python3 -m pip install -r requirements.txt && python3 -m unittest discover -s pipeline"
