name: build-and-push
description: A plugin to help with building, publishing and scanning container images
author: Dylan Smith
requirements:
  - docker
configuration:
  properties:
    dockerfile-path:
      type: string
    context-path:
      type: string
    image-tag:
      type: string
    additional-tag:
      type: string
    image-name:
      type: string
    build-args:
      type: string
    build-x86:
      type: boolean
    build-arm:
      type: boolean
    scan-image:
      type: boolean
    group-key:
      type: string
    always-pull:
      type: boolean
    composer-cache:
      type: boolean
    npm-cache:
      type: boolean
    yarn-cache:
      type: boolean
    push-branches:
      type: string
    repository-namespace:
      type: string
    mutate-image-tag:
      type: boolean
    additional-plugins:
      type: array
  required: []
  additionalProperties: false
