steps:
  - group: Lint
    key: lint
    steps:
      - command: make lint-plugin
        label: ":buildkite: Lint plugin configuration"
      
      - command: make lint-shell
        label: ":bash: Lint scripts"

      - command: make lint-python
        label: ":python: Lint scripts"
        key: lint-python

  - group: Tests
    depends_on:
      - lint
    steps:
      - command: make tests
        label: ":python: Test scripts"

      - label: ":python: Test integration"
        trigger: echoserver
        build:
          message: "Triggered from ${BUILDKITE_PIPELINE_NAME}: ${BUILDKITE_MESSAGE}"
          branch: master
          env:
            BUILD_AND_PUSH_BUILDKITE_PLUGIN_VERSION: ${BUILDKITE_TAG:-${BUILDKITE_COMMIT:0:10}}
