steps:
  - group: Lint
    steps:
      - command: make lint-plugin
        label: "Lint :buildkite: plugin configuration"
      
      - command: make lint-shell
        label: "Lint :bash: scripts"

      - command: make lint-python
        label: "Lint :python: scripts"
        key: lint-python

  - group: Tests
    steps:
      - command: make tests
        label: "Test :python: tests"
        depends_on: lint-python
